# Extends the mainnet preset
PRESET_BASE = "mainnet"
CONFIG_NAME = "testnet" # needs to exist because of Prysm. Otherwise it conflicts with mainnet genesis

# Genesis
# ---------------------------------------------------------------
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT = 64 # `2**14` (= 16,384)
MIN_GENESIS_TIME = 1732215600 # 2024-Nov-21 07:00:00 PM UTC
GENESIS_FORK_VERSION = "0x1000101b"
GENESIS_DELAY = 600

# Forking
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

ALTAIR_FORK_VERSION = "0x2000101b"
ALTAIR_FORK_EPOCH = 0

BELLATRIX_FORK_VERSION = "0x3000101b"
BELLATRIX_FORK_EPOCH = 0
TERMINAL_TOTAL_DIFFICULTY = 0
TERMINAL_BLOCK_HASH = "0x0000000000000000000000000000000000000000000000000000000000000000"
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH = 18446744073709551615

CAPELLA_FORK_VERSION = "0x4000101b"
CAPELLA_FORK_EPOCH = 0

DENEB_FORK_VERSION = "0x5000101b"
DENEB_FORK_EPOCH = 0

ELECTRA_FORK_VERSION = "0x6000101b"
ELECTRA_FORK_EPOCH = 18446744073709551615

EIP7594_FORK_VERSION = "0x7000101b"
EIP7594_FORK_EPOCH = 18446744073709551615

# Time parameters
# ---------------------------------------------------------------
SECONDS_PER_SLOT = 12 # 12 seconds
SECONDS_PER_ETH1_BLOCK = 12 # 14 (estimate from Eth1 mainnet)
MIN_VALIDATOR_WITHDRAWABILITY_DELAY = 256 # 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD = 256 # 2**8 (= 256) epochs ~27 hours
ETH1_FOLLOW_DISTANCE = 12 # 2**11 (= 2,048) Eth1 blocks ~8 hours

# Validator cycle
# ---------------------------------------------------------------
INACTIVITY_SCORE_BIAS = 4 # 2**2 (= 4)
INACTIVITY_SCORE_RECOVERY_RATE = 16 # 2**4 (= 16)
EJECTION_BALANCE = 30000000000 # 2**4 * 10**9 (= 16,000,000,000) Gwei
MIN_PER_EPOCH_CHURN_LIMIT = 4 # 2**2 (= 4)
CHURN_LIMIT_QUOTIENT = 65536 # 2**16 (= 65,536)
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT = 8 # [New in Deneb:EIP7514] 2**3 (= 8)

# Fork choice
# ---------------------------------------------------------------
PROPOSER_SCORE_BOOST = 40 # 40%
REORG_HEAD_WEIGHT_THRESHOLD = 20 # 20%
REORG_PARENT_WEIGHT_THRESHOLD = 160 # 160%
REORG_MAX_EPOCHS_SINCE_FINALIZATION = 2 # `2` epochs

# Deposit contract
# ---------------------------------------------------------------
DEPOSIT_CHAIN_ID = 39438140
DEPOSIT_NETWORK_ID = 39438140
DEPOSIT_CONTRACT_ADDRESS = "0x4242424242424242424242424242424242424242"

# Networking
# ---------------------------------------------------------------
GOSSIP_MAX_SIZE = 10485760 # `10 * 2**20` (= 10485760, 10 MiB)
MAX_REQUEST_BLOCKS = 1024 # `2**10` (= 1024)
EPOCHS_PER_SUBNET_SUBSCRIPTION = 256 # `2**8` (= 256)
MIN_EPOCHS_FOR_BLOCK_REQUESTS = 33024 # `MIN_VALIDATOR_WITHDRAWABILITY_DELAY + CHURN_LIMIT_QUOTIENT // 2` (~5 months)
MAX_CHUNK_SIZE = 10485760 # `10 * 2**20` (=10485760, 10 MiB)
TTFB_TIMEOUT = 5 # 5s
RESP_TIMEOUT = 10 # 10s
ATTESTATION_PROPAGATION_SLOT_RANGE = 32
MAXIMUM_GOSSIP_CLOCK_DISPARITY = 500 # 500ms
MESSAGE_DOMAIN_INVALID_SNAPPY = "0x00000000"
MESSAGE_DOMAIN_VALID_SNAPPY = "0x01000000"
SUBNETS_PER_NODE = 2 # 2 subnets per node
ATTESTATION_SUBNET_COUNT = 64 # `2**8 (= 64)`
ATTESTATION_SUBNET_EXTRA_BITS = 0
ATTESTATION_SUBNET_PREFIX_BITS = 6 # ceillog2(ATTESTATION_SUBNET_COUNT) + ATTESTATION_SUBNET_EXTRA_BITS

# Deneb
MAX_REQUEST_BLOCKS_DENEB = 128 # `2**7` (=128)
MAX_REQUEST_BLOB_SIDECARS = 768 # MAX_REQUEST_BLOCKS_DENEB * MAX_BLOBS_PER_BLOCK
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS = 4096 # `2**12` (~18 days)
BLOB_SIDECAR_SUBNET_COUNT = 6 # `6`

# Whisk
WHISK_EPOCHS_PER_SHUFFLING_PHASE = 256 # `Epoch(2**8)`
WHISK_PROPOSER_SELECTION_GAP = 2 # `Epoch(2)`

# EIP7594
NUMBER_OF_COLUMNS = 128
MAX_CELLS_IN_EXTENDED_MATRIX = 768
DATA_COLUMN_SIDECAR_SUBNET_COUNT = 32
MAX_REQUEST_DATA_COLUMN_SIDECARS = 16384
SAMPLES_PER_SLOT = 8
CUSTODY_REQUIREMENT = 1
TARGET_NUMBER_OF_PEERS = 70

# [New in Electra:EIP7251]
MIN_PER_EPOCH_CHURN_LIMIT_ELECTRA = 128000000000 # 2**7 * 10**9 (= 128,000,000,000)
MAX_PER_EPOCH_ACTIVATION_EXIT_CHURN_LIMIT = 256000000000 # 2**8 * 10**9 (= 256,000,000,000)
